export const ROUTE_PATHS = {
  login: '/',
  dashboard: '/dashboard',
  adminDashboard: '/admin-dashboard',
  managerDashboard: '/manager-dashboard',
  managerProfile: '/manager/profile',
  users: '/users',
  auditLogs: '/admin/audit-logs',
  adminNotifications: '/admin/notifications',
  adminProfile: '/admin/profile',
  notifications: '/notifications',
  profile: '/profile',
  vehicleEntry: '/vehicle-entry',
  manualSlot: '/vehicle-entry/manual-slot',
  aiRecommendation: '/ai-recommendation',
  checkinSuccess: '/vehicle-entry/success',
  parkingMap: '/parking-map',
  vehicleExit: '/vehicle-exit',
  vehicleExitSuccess: '/vehicle-exit/success',
  payment: '/payment',
  tickets: '/tickets',
  parkingStructure: '/parking-structure',
  pricing: '/pricing',
  reports: '/reports',
  dailyOperationsReport: '/reports/daily-operations',
  staffActivity: '/staff-activity',
  monthlyPass: '/monthly-pass',
  reservation: '/reservation',
  lostTicket: '/lost-ticket',
  systemLogs: '/system-logs',
  driverPortal: '/driver',
  driverParkVehicle: '/driver/park-vehicle',
  driverReceiveTicket: '/driver/receive-ticket',
  driverPayFee: '/driver/receive-ticket?tab=pay-fee',
  driverMonthlyPass: '/driver/monthly-pass',
  driverReservation: '/driver/reservation',
}

