export const ROUTE_PATHS = {
  login: '/',
  dashboard: '/dashboard',
  adminDashboard: '/admin-dashboard',
  notifications: '/notifications',
  profile: '/profile',
  vehicleEntry: '/vehicle-entry',
  manualSlot: '/vehicle-entry/manual-slot',
  aiRecommendation: '/ai-recommendation',
  checkinSuccess: '/vehicle-entry/success',
  parkingMap: '/parking-map',
  vehicleExit: '/vehicle-exit',
  vehicleExitSuccess: '/vehicle-exit/success',
  payment: '/payment',
  tickets: '/tickets',
  parkingStructure: '/parking-structure',
  pricing: '/pricing',
  monthlyPass: '/monthly-pass',
  reservation: '/reservation',
  lostTicket: '/lost-ticket',
  systemLogs: '/system-logs',
}
