export const managerProfileData = {
  initials: 'M',
  name: 'Nguyễn Hoàng Minh',
  role: 'Parking Facility Manager',
  title: 'Operations Manager',
  managerId: 'MGR-2026-001',
  facility: 'Building A',
  department: 'Facility Operations',
  email: 'manager@parking.com',
  phone: '0901 234 568',
  status: 'Active',
  lastLogin: 'Today 11:20',
  responsibility: [
    ['Facility', 'Building A'],
    ['Coverage', '4 floors · 12 zones'],
    ['Staff on duty', '8 / 9 assigned'],
    ['Operation mode', 'Normal'],
  ],
  security: [
    ['Account status', 'Active'],
    ['Current session', 'Active'],
    ['Login method', 'Manager account'],
    ['Device', 'Operations workstation'],
    ['Last login', 'Today 11:20'],
  ],
  permissions: {
    allowed: ['Manager Dashboard', 'Parking Structure', 'Pricing Rules', 'Reports', 'Staff Activity'],
    limited: [
      ['Payment records', 'Review only'],
      ['Lost ticket cases', 'Manager review'],
      ['Facility map', 'View and monitor'],
    ],
    denied: ['Users & Roles', 'Audit Logs', 'Account Permissions'],
  },
  activities: [
    ['Today 17:35', 'Daily operations report exported', 'RPT-2026-00012', 'Completed'],
    ['Today 17:30', 'Daily operations report reviewed', 'RPT-2026-00012', 'Completed'],
    ['Today 16:45', 'Pending payment case reviewed', 'PAY-000129', 'Pending'],
    ['Today 15:20', 'Zone B capacity checked', 'Zone B', 'Completed'],
  ],
}
