export const reservationItems = [
  {
    id: 1,
    code: 'RSV-2026-00045',
    driver: 'Nguyen Van A',
    plate: '51A-12345',
    type: 'Car',
    slot: 'B2-18',
    floor: 'Floor 2',
    zone: 'Zone B',
    status: 'Pending',
    payment: 'Paid',
    reservedSlotStatus: 'Slot is currently empty',
    arrivalWindow: '14:30 - 15:00',
    checkInDeadline: '15:00',
    noShowRisk: 'Low',
    gate: 'Entry Gate A',
    staff: 'Nguyen Van A',
    activityNote: 'Active reservation',
  },
  {
    id: 2,
    code: 'RSV-2026-00048',
    driver: 'Tran Minh B',
    plate: '30A-99887',
    type: 'EV',
    slot: 'EV-04',
    floor: 'Floor 1',
    zone: 'Zone A',
    status: 'Pending',
    payment: 'Unpaid',
    reservedSlotStatus: 'Reserved EV slot',
    arrivalWindow: '15:00 - 15:20',
    checkInDeadline: '15:20',
    noShowRisk: 'Medium',
    gate: 'Entry Gate A',
    staff: 'Tran Minh B',
    activityNote: 'EV registered',
  },
  {
    id: 3,
    code: 'RSV-2026-00047',
    driver: 'Le Hoang C',
    plate: '61C-23111',
    type: 'Motorcycle',
    slot: 'M-12',
    floor: 'Floor 3',
    zone: 'Zone C',
    status: 'Checked In',
    payment: 'Paid',
    reservedSlotStatus: 'Slot occupied by reservation',
    arrivalWindow: '14:20 - 14:40',
    checkInDeadline: '14:40',
    noShowRisk: 'Low',
    gate: 'Entry Gate A',
    staff: 'Le Hoang C',
    activityNote: 'Checked in successfully',
  },
  {
    id: 4,
    code: 'RSV-2026-00049',
    driver: 'Pham Gia Huy',
    plate: '59A-77123',
    type: 'Car',
    slot: 'B1-02',
    floor: 'Floor 1',
    zone: 'Zone B',
    status: 'Cancelled',
    payment: 'Refunded',
    reservedSlotStatus: 'Slot released',
    arrivalWindow: '13:00 - 13:20',
    checkInDeadline: '13:20',
    noShowRisk: 'High',
    gate: 'Entry Gate A',
    staff: 'Pham Gia Huy',
    activityNote: 'Reservation cancelled by driver',
  },
]

export const upcomingArrivals = [
  { time: '15:00', slot: 'EV-04' },
  { time: '15:10', slot: 'M-12' },
  { time: '15:20', slot: 'B1-09' },
  { time: '15:30', slot: 'B3-06' },
]

export const reservationActivities = [
  { time: '14:15:22', code: 'RSV-2026-00046', plate: '30A-99887', action: 'Checked In', staff: 'System', status: 'Completed' },
  { time: '14:05:33', code: 'RSV-2026-00045', plate: '51A-12345', action: 'Reminder Sent', staff: 'Parking Staff', status: 'Pending' },
  { time: '13:50:05', code: 'RSV-2026-00042', plate: '59A-77123', action: 'Cancelled by Driver', staff: 'System', status: 'Cancelled' },
]
