import { useMemo } from 'react'
import { useNavigate } from 'react-router-dom'
import MainLayout from '../../layouts/MainLayout'
import { ROUTE_PATHS } from '../../routes/routePaths'
import { getDailyOperationsDetail } from './reportsService'
import './DailyOperationsReportPage.css'

function DailyOperationsReportPage() {
  const navigate = useNavigate()
  const detail = useMemo(() => getDailyOperationsDetail(), [])

  return (
    <MainLayout>
      <div className="daily-report-page">
        <header className="daily-report-header">
          <div className="daily-report-breadcrumb">
            <button type="button" onClick={() => navigate(ROUTE_PATHS.reports)}>Reports</button>
            <span className="material-symbols-outlined">chevron_right</span>
            <strong>Daily Operations Report Detail</strong>
          </div>
          <div>
            <h1>Daily Operations Report Detail</h1>
            <p>View detailed operational metrics, revenue breakdown, ticket activity, and report notes for today's daily operations report.</p>
          </div>
        </header>

        <section className="daily-report-summary-grid">
          <div className="report-summary-card"><span>Report Name</span><strong>{detail.metadata.reportName}</strong></div>
          <div className="report-summary-card"><span>Date Range</span><strong>{detail.metadata.dateRange}</strong></div>
          <div className="report-summary-card"><span>Building</span><strong>{detail.metadata.building}</strong></div>
          <div className="report-summary-card"><span>Generated By</span><strong>{detail.metadata.generatedBy}</strong></div>
          <div className="report-summary-card"><span>Generated At</span><strong>{detail.metadata.generatedAt}</strong></div>
          <div className="report-summary-card"><span>Status</span><strong>{detail.metadata.status}</strong></div>
        </section>

        <div className="daily-report-grid">
          <section className="daily-report-metrics-card">
            <div className="section-header"><h2>Operation Metrics</h2></div>
            <div className="table-wrap">
              <table className="detail-table">
                <thead>
                  <tr>
                    <th>Metric</th>
                    <th>Today</th>
                    <th>Yesterday</th>
                    <th>Change</th>
                    <th>Status</th>
                  </tr>
                </thead>
                <tbody>
                  {detail.metrics.map((item) => (
                    <tr key={item.metric}>
                      <td>{item.metric}</td>
                      <td>{item.today}</td>
                      <td>{item.yesterday}</td>
                      <td>{item.change}</td>
                      <td><span className={`detail-status-pill ${item.status.toLowerCase()}`}>{item.status}</span></td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </section>

          <aside className="daily-report-insights-card">
            <div className="section-header"><h2>Key Findings</h2></div>
            <ul className="insight-list">
              {detail.keyFindings.map((item) => <li key={item}>{item}</li>)}
            </ul>
            <div className="section-header"><h2>Recommended Actions</h2></div>
            <ul className="insight-list">
              {detail.recommendedActions.map((item) => <li key={item}>{item}</li>)}
            </ul>
          </aside>
        </div>

        <div className="daily-report-grid">
          <section className="daily-report-card">
            <div className="section-header"><h2>Revenue Breakdown</h2></div>
            <div className="table-wrap">
              <table className="detail-table">
                <thead>
                  <tr>
                    <th>Source</th>
                    <th>Amount</th>
                    <th>Share</th>
                    <th>Status</th>
                  </tr>
                </thead>
                <tbody>
                  {detail.revenueBreakdown.map((item) => (
                    <tr key={item.source}>
                      <td>{item.source}</td>
                      <td>{item.amount}</td>
                      <td>{item.share}</td>
                      <td><span className={`detail-status-pill ${item.status.toLowerCase()}`}>{item.status}</span></td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </section>

          <section className="daily-report-card">
            <div className="section-header"><h2>Ticket Activity</h2></div>
            <div className="table-wrap">
              <table className="detail-table">
                <thead>
                  <tr>
                    <th>Ticket Type</th>
                    <th>Count</th>
                    <th>Revenue</th>
                    <th>Status</th>
                  </tr>
                </thead>
                <tbody>
                  {detail.ticketActivity.map((item) => (
                    <tr key={item.type}>
                      <td>{item.type}</td>
                      <td>{item.count}</td>
                      <td>{item.revenue}</td>
                      <td><span className={`detail-status-pill ${item.status.toLowerCase()}`}>{item.status}</span></td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </section>
        </div>

        <section className="daily-report-history-card">
          <div className="section-header"><h2>Recent Export Activity</h2></div>
          <div className="table-wrap">
            <table className="detail-table">
              <thead>
                <tr>
                  <th>Time</th>
                  <th>Report</th>
                  <th>Action</th>
                  <th>Staff</th>
                  <th>Status</th>
                </tr>
              </thead>
              <tbody>
                {detail.exportHistory.map((item) => (
                  <tr key={`${item.time}-${item.report}`}>
                    <td>{item.time}</td>
                    <td>{item.report}</td>
                    <td>{item.action}</td>
                    <td>{item.staff}</td>
                    <td><span className="update-pill">{item.status}</span></td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </section>
      </div>
    </MainLayout>
  )
}

export default DailyOperationsReportPage
