import { useEffect, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import ManagerLayout from '../../layouts/ManagerLayout'
import { ROUTE_PATHS } from '../../routes/routePaths'
import { exportReport } from './reportsService'
import { getDailyOperationsReport, reviewDailyOperationsReport } from './dailyOperationsReportService'
import './DailyOperationsReportPage.css'

function Status({ children }) {
  return <span className={`document-status ${children.toLowerCase().replaceAll(' ', '-')}`}>{children}</span>
}

function DetailGroup({ title, children }) {
  return <section className="breakdown-group"><h4>{title}</h4><div>{children}</div></section>
}

function DetailRow({ label, value, note }) {
  return <div className="breakdown-row"><span>{label}{note && <small>{note}</small>}</span><strong>{value}</strong></div>
}

function DailyOperationsReportPage() {
  const navigate = useNavigate()
  const [data, setData] = useState(null)
  const [reviewed, setReviewed] = useState(false)
  const [notice, setNotice] = useState('')

  useEffect(() => { getDailyOperationsReport().then(setData) }, [])
  const notify = (message) => { setNotice(message); window.setTimeout(() => setNotice(''), 2500) }
  const handleExport = async (type) => { await exportReport(data.report.id, type); notify(`${data.report.id} exported as ${type} in mock mode.`) }
  const reviewReport = async (action) => {
    await reviewDailyOperationsReport(data.report.id, action)
    if (action === 'reviewed') setReviewed(true)
    notify(action === 'reviewed' ? 'Report marked as reviewed.' : 'Report sent to Operations Team.')
  }

  if (!data) return <ManagerLayout><div className="daily-loading">Loading report detail...</div></ManagerLayout>

  const report = data.report
  const vehicleFlow = [
    ['Entries', '284'], ['Exits', '271'], ['Active Tickets', '128'], ['Average Duration', '3h 10m'],
  ]

  return <ManagerLayout>
    <div className="daily-report-page">
      <header className="daily-heading">
        <p>Dashboard <span>/</span> Reports <span>/</span> Daily Operations Report Detail</p>
        <h1>Daily Operations Report Detail</h1>
        <h2>Review detailed daily parking operations, revenue, occupancy, ticket activity, and operational issues.</h2>
      </header>

      <section className="daily-report-header">
        <div className="report-header-fields">
          <div><small>Report ID</small><strong>{report.id}</strong></div><div><small>Report Type</small><strong>{report.type}</strong></div><div><small>Facility</small><strong>{report.facility}</strong></div><div><small>Report Date</small><strong>{report.date}</strong></div><div><small>Generated</small><strong>{report.time}</strong></div><div><small>Generated By</small><strong>{report.generatedBy}</strong></div><div><small>Status</small><Status>{reviewed ? 'Reviewed' : report.status}</Status></div>
        </div>
        <div className="report-header-actions"><button onClick={() => navigate(ROUTE_PATHS.reports)}>Back to Reports</button><button className="primary" onClick={() => handleExport('PDF')}>Export PDF</button><button onClick={() => handleExport('Excel')}>Export Excel</button></div>
      </section>

      <article className="report-document">
        <section className="executive-summary document-section">
          <header><span>01</span><div><h3>Executive Summary</h3><p>Daily operational assessment</p></div></header>
          <p>{data.executiveSummary}</p>
          <p className="overall-assessment"><strong>Overall assessment:</strong> Stable operation with 3 pending reviews requiring manager attention.</p>
        </section>

        <section className="document-metrics document-section">
          <header><span>02</span><div><h3>Key Metrics</h3><p>Building A · Today</p></div></header>
          <div>{data.kpis.map((item) => <article key={item.label}><small>{item.label}</small><strong className={item.tone ?? ''}>{item.value}</strong></article>)}</div>
        </section>

        <section className="operations-breakdown document-section">
          <header><span>03</span><div><h3>Operations Breakdown</h3><p>Revenue, vehicle flow, occupancy, and ticket volume</p></div></header>
          <div className="breakdown-grid">
            <DetailGroup title="Revenue">{data.revenue.slice(1).map((item) => <DetailRow key={item.label} label={item.label.replace(' Payment', '')} value={item.value} />)}</DetailGroup>
            <DetailGroup title="Vehicle Flow">{vehicleFlow.map(([label, value]) => <DetailRow key={label} label={label} value={value} />)}</DetailGroup>
            <DetailGroup title="Occupancy">{data.zones.map((item) => <DetailRow key={item.zone} label={`${item.zone} · ${item.type}`} value={item.occupancy} note={item.status === 'High' ? 'High occupancy' : ''} />)}</DetailGroup>
            <DetailGroup title="Tickets">{data.tickets.map((item) => <DetailRow key={item.type} label={item.type} value={String(item.count)} />)}</DetailGroup>
          </div>
        </section>

        <div className="document-review-grid document-section">
          <section className="issues-review">
            <header><span>04</span><div><h3>Issues Requiring Review</h3><p>Items to resolve before final closing</p></div></header>
            <div>{data.issues.map((item) => <article key={item.issue}><div><strong>{item.issue}</strong><p>{item.detail}</p></div><Status>{item.priority}</Status></article>)}</div>
          </section>

          <section className="manager-notes">
            <header><span>05</span><div><h3>Manager Notes</h3><p>Internal review comment</p></div></header>
            <blockquote>{data.managerNote}</blockquote>
            <div className="approval-details"><span>Reviewed By<strong>Parking Facility Manager</strong></span><span>Review Status<strong>{reviewed ? 'Reviewed' : 'Waiting for final review'}</strong></span><span>Last Updated<strong>Today 17:35</strong></span></div>
            <div className="approval-actions"><button className="primary" onClick={() => reviewReport('reviewed')}>Mark Report Reviewed</button><button onClick={() => reviewReport('sent')}>Send to Operations Team</button></div>
          </section>
        </div>

        <section className="related-activities document-section">
          <header><span>06</span><div><h3>Recent Related Activities</h3><p>Latest events referenced by this report</p></div></header>
          <div className="activity-list">{data.activities.slice(0, 3).map((item) => <article key={`${item.time}-${item.reference}`}><time>{item.time}</time><div><strong>{item.activity}</strong><span>{item.reference} · {item.staff}</span></div><Status>{item.status}</Status></article>)}</div>
        </section>
      </article>

      {notice && <div className="daily-notice" role="status">{notice}</div>}
    </div>
  </ManagerLayout>
}

export default DailyOperationsReportPage
