import { useMemo } from 'react'
import { useNavigate } from 'react-router-dom'
import MainLayout from '../../layouts/MainLayout'
import { ROUTE_PATHS } from '../../routes/routePaths'
import { getDailyOperationsDetail } from './reportsService'
import './DailyOperationsReportPage.css'

function getChangeClass(change) {
  if (change.startsWith('+') && parseFloat(change) >= 100) return 'change-high'
  if (change.startsWith('+') && parseFloat(change) >= 50) return 'change-warning'
  if (change.startsWith('+')) return 'change-positive'
  return ''
}

function getMetricStatusClass(status) {
  const map = {
    Improved: 'status-improved',
    Normal: 'status-normal',
    Review: 'status-warning',
    High: 'status-error',
    Monitor: 'status-warning',
  }
  return map[status] || 'status-normal'
}

function getDetailStatusClass(status) {
  const map = {
    Active: 'status-active',
    Reviewed: 'status-reviewed',
    Pending: 'status-warning',
  }
  return map[status] || 'status-normal'
}

const keyFindings = [
  'Revenue increased compared to yesterday.',
  'Lost ticket cases are higher than normal.',
  'Floor 1 occupancy should be monitored.',
  'Manual slot overrides increased during the current shift.',
]

function DailyOperationsReportPage() {
  const navigate = useNavigate()
  const detail = useMemo(() => getDailyOperationsDetail(), [])

  return (
    <MainLayout>
      <div className="daily-report-page">
        <header className="daily-report-header">
          <nav className="daily-report-breadcrumb" aria-label="Breadcrumb">
            <button type="button" onClick={() => navigate(ROUTE_PATHS.dashboard)}>Dashboard</button>
            <span className="material-symbols-outlined">chevron_right</span>
            <button type="button" onClick={() => navigate(ROUTE_PATHS.reports)}>Reports</button>
            <span className="material-symbols-outlined">chevron_right</span>
            <strong>Daily Operations Report Detail</strong>
          </nav>
          <h1>Daily Operations Report Detail</h1>
          <p>View detailed operational metrics, revenue breakdown, ticket activity, and report notes for the selected report.</p>
        </header>

        <section className="daily-report-meta-card">
          <div className="meta-fields">
            <div className="meta-field">
              <span>Report Name</span>
              <strong>{detail.metadata.reportName}</strong>
            </div>
            <div className="meta-field">
              <span>Date Range</span>
              <strong>{detail.metadata.dateRange}</strong>
            </div>
            <div className="meta-field">
              <span>Building</span>
              <strong>{detail.metadata.building}</strong>
            </div>
            <div className="meta-field">
              <span>Generated By</span>
              <strong>{detail.metadata.generatedBy}</strong>
            </div>
            <div className="meta-field">
              <span>Generated At</span>
              <strong>{detail.metadata.generatedAt}</strong>
            </div>
            <div className="meta-field">
              <span>Status</span>
              <span className="status-ready-pill">READY</span>
            </div>
          </div>
          <div className="meta-actions">
            <button type="button" className="button-secondary" onClick={() => navigate(ROUTE_PATHS.reports)}>
              Back to Reports
            </button>
            <button type="button" className="button-primary">Export PDF</button>
            <button type="button" className="button-secondary">Export Excel</button>
          </div>
        </section>

        <section className="daily-report-main-grid">
          <div className="daily-report-metrics-card">
            <div className="section-header">
              <h2>Operation Metrics</h2>
            </div>
            <div className="table-wrap">
              <table className="detail-table">
                <thead>
                  <tr>
                    <th>Metric</th>
                    <th>Today</th>
                    <th>Yesterday</th>
                    <th>Change</th>
                    <th>Status</th>
                  </tr>
                </thead>
                <tbody>
                  {detail.metrics.map((item) => (
                    <tr key={item.metric}>
                      <td className="cell-metric">{item.metric}</td>
                      <td>{item.today}</td>
                      <td>{item.yesterday}</td>
                      <td className={getChangeClass(item.change)}>{item.change}</td>
                      <td>
                        <span className={`status-text ${getMetricStatusClass(item.status)}`}>
                          {item.status}
                        </span>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>

          <aside className="daily-report-insights-column">
            <div className="insight-card">
              <h3>Key Findings</h3>
              <ul className="insight-list">
                {keyFindings.map((item) => <li key={item}>{item}</li>)}
              </ul>
            </div>
            <div className="insight-card">
              <h3>Recommended Actions</h3>
              <ul className="insight-list">
                {detail.recommendedActions.map((item) => <li key={item}>{item}</li>)}
              </ul>
            </div>
          </aside>
        </section>

        <section className="daily-report-bottom-grid">
          <div className="daily-report-card">
            <div className="section-header">
              <h2>Revenue Breakdown</h2>
            </div>
            <div className="table-wrap">
              <table className="detail-table">
                <thead>
                  <tr>
                    <th>Source</th>
                    <th>Amount</th>
                    <th>Share</th>
                    <th>Status</th>
                  </tr>
                </thead>
                <tbody>
                  {detail.revenueBreakdown.map((item) => (
                    <tr key={item.source}>
                      <td className="cell-metric">{item.source}</td>
                      <td>{item.amount}</td>
                      <td>{item.share}</td>
                      <td>
                        <span className={`status-text ${getDetailStatusClass(item.status)}`}>
                          {item.status}
                        </span>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>

          <div className="daily-report-card">
            <div className="section-header">
              <h2>Ticket Activity</h2>
            </div>
            <div className="table-wrap">
              <table className="detail-table">
                <thead>
                  <tr>
                    <th>Ticket Type</th>
                    <th>Count</th>
                    <th>Revenue</th>
                    <th>Status</th>
                  </tr>
                </thead>
                <tbody>
                  {detail.ticketActivity.map((item) => (
                    <tr key={item.type}>
                      <td className="cell-metric">{item.type}</td>
                      <td>{item.count}</td>
                      <td>{item.revenue}</td>
                      <td>
                        <span className={`status-text ${getDetailStatusClass(item.status)}`}>
                          {item.status}
                        </span>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>
        </section>
      </div>
    </MainLayout>
  )
}

export default DailyOperationsReportPage
